version: '3.4'

services:
  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: AuctionService/Dockerfile
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=sujan6861
    ports:
        - 5432:5432
    volumes:
        - pgdata:/var/lib/postgresql/data  
volumes:
    pgdata:


