version: '3.4'

services:
  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: AuctionService/Dockerfile
  postgres:
    image: postgres
    environment:
        - POSTGRES_PASSWORD=sujan6861
    ports:
        - 5432:5432
    volumes:
        - /var/lib/postgresql/data  
  searchservice:
    image: ${DOCKER_REGISTRY-}searchservice
    build:
      context: .
      dockerfile: SearchService/Dockerfile
  mongodb:
    image: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=sujan6861
    ports:
        - 27017:27017
    volumes:
        - /data/db



